name       : kcolorpicker
version    : 0.1.4
release    : 1
source     :
    - https://github.com/ksnip/kColorPicker/archive/v0.1.4.tar.gz : 3036d00cce2a8cc6a0bc87a9a3ff629e21adbdaa509e41f23a2ef1661d537c72
license    : LGPL-3.0-only
component  : desktop.qt
summary    : Qt based Color Picker with popup menu
description: |
    Qt based Color Picker with popup menu
builddeps  :
    - pkgconfig(Qt5Core)
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
