name       : kcolorpicker
version    : 0.1.5
release    : 2
source     :
    - https://github.com/ksnip/kColorPicker/archive/refs/tags/v0.1.5.tar.gz : fe6f6c540f3921cc7097f1e5cf001883f814a9c2678c85b7f78fb7a2ba2a8c34
license    : LGPL-3.0-only
component  : desktop.qt
summary    : Qt based Color Picker with popup menu
description: |
    Qt based Color Picker with popup menu
builddeps  :
    - pkgconfig(Qt5Core)
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
