name       : kcolorpicker
version    : 0.1.6
release    : 3
source     :
    - https://github.com/ksnip/kColorPicker/archive/refs/tags/v0.1.6.tar.gz : a167b081d444c54057f587782b81bf0f057b50e34e8a2d074e88007387007e91
license    : LGPL-3.0-only
component  : desktop.qt
summary    : Qt based Color Picker with popup menu
description: |
    Qt based Color Picker with popup menu
builddeps  :
    - pkgconfig(Qt5Core)
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
